export const TABLE_DATA_REQUESTED = 'TABLE_DATA_REQUESTED';
export const TABLE_DATA_RECEIVED = 'TABLE_DATA_RECEIVED';
export const SAVE_NEEDED = 'SAVE_NEEDED';
export const SAVE_FINISHED = 'SAVE_FINISHED';