export const TABLE_DATA_REQUESTED = 'TABLE_DATA_REQUESTED';
export const TABLE_DATA_RECEIVED = 'TABLE_DATA_RECEIVED';
export const SAVE_NEEDED = 'SAVE_NEEDED';
export const SAVE_FINISHED = 'SAVE_FINISHED';
export const CATEGORY_DATA_REQUESTED = 'CATEGORY_DATA_REQUESTED';
export const CATEGORY_DATA_RECEIVED = 'CATEGORY_DATA_RECEIVED';
export const MONTHLY_DATA_REQUESTED = 'MONTHLY_DATA_REQUESTED';
export const MONTHLY_DATA_RECEIVED = 'MONTHLY_DATA_RECEIVED';